#!/usr/bin/env python
from smtplib import SMTP
from smtplib import SMTPException
from email.mime.text import MIMEText
import sys

'''
  Borrowed from here (https://github.com/rakeshcusat/Code4Reference/blob/master/PythonPrograms/GmailSendEmail.py)
  Edited to suit my own needs.
'''
 
#Global varialbes
EMAIL_SUBJECT = "Subject"
EMAIL_SENDER  =  "sample@gmail.com"
GMAIL_SMTP = "smtp.gmail.com"
GMAIL_SMTP_PORT = 587
TEXT_SUBTYPE = "plain"
PASSWORD = "password"
 
def send_email(content, recipients):
    """This method sends an email"""    
     
    #Create the message
    message = MIMEText(content, TEXT_SUBTYPE)
    message["Subject"] = EMAIL_SUBJECT
    message["From"] = EMAIL_SENDER
    message["To"] = ','.join(recipients)
     
    try:
      smtpObj = SMTP(GMAIL_SMTP, GMAIL_SMTP_PORT)
      #Identify yourself to GMAIL ESMTP server.
      smtpObj.ehlo()
      #Put SMTP connection in TLS mode and call ehlo again.
      smtpObj.starttls()
      smtpObj.ehlo()
      #Login to service
      smtpObj.login(user=EMAIL_SENDER, password=pswd)
      #Send email
      smtpObj.sendmail(EMAIL_SENDER, recipients, message.as_string())
      #close connection and session.
      smtpObj.quit();
    except SMTPException as error:
      print "Error: unable to send email :  {err}".format(err=error)
 
def main(pswd):
    """This is a simple main() function which demonstrates sending of email using smtplib."""
    send_email("Test email was generated by Python using smtplib and email libraries", pswd);
 
if __name__ == "__main__":
    """If this script is executed as stand alone then call main() function."""
    if len(sys.argv) == 2:
        main(sys.argv[1])
    else:
        print "Please provide password"
        sys.exit(0)